openapi: 3.1.0
info:
  title: Trade Router Proxy
  version: 1.0.0
  description: Forwarding contract for trade-prefixed routes served by the gateway.
paths:
  /v1/trade/{proxyPath}:
    parameters:
      - name: proxyPath
        in: path
        description: Remaining path segments forwarded to the trade service.
        required: true
        schema:
          type: string
    get:
      summary: Forward trade read requests
      description: Forwards GET requests to the trade upstream and streams the response back to the client.
      tags:
        - Trade
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response from the upstream trade service.
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/ForbiddenError'
        '502':
          $ref: '#/components/responses/BadGatewayError'
    post:
      summary: Forward trade mutating requests
      description: Forwards non-idempotent trade requests (e.g. POST) to the upstream service with idempotency handled by the caller.
      tags:
        - Trade
      security:
        - bearerAuth: []
      requestBody:
        description: JSON payload forwarded to the trade backend.
        required: false
        content:
          application/json:
            schema:
              type: object
      responses:
        '201':
          description: Resource created by the trade backend.
        '202':
          description: Request accepted for asynchronous processing.
        '400':
          $ref: '#/components/responses/BadRequestError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/ForbiddenError'
        '502':
          $ref: '#/components/responses/BadGatewayError'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas: {}
  responses:
    UnauthorizedError:
      description: Missing or invalid bearer token.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ProblemJson'
          examples:
            missingToken:
              value:
                type: about:blank
                title: Authentication Required
                status: 401
                detail: Missing Authorization header
                traceId: 2ad1d935-6a7a-4c44-8e7d-719040ea74f0
    ForbiddenError:
      description: Caller lacks required trade scopes.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ProblemJson'
          examples:
            scopeMismatch:
              value:
                type: about:blank
                title: Insufficient Scope
                status: 403
                detail: trade.write scope required
                traceId: 10b8f2bf-8f64-449b-a1eb-b0abf3b3c556
    BadGatewayError:
      description: Upstream trade service is unavailable.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ProblemJson'
          examples:
            upstreamDown:
              value:
                type: about:blank
                title: Upstream Service Unavailable
                status: 502
                detail: Failed to reach trade service
                traceId: 891d7efd-a5c1-4b4f-9649-93aefc3662b5
    BadRequestError:
      description: Upstream validation failed.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ProblemJson'
          examples:
            validationError:
              value:
                type: about:blank
                title: Bad Request
                status: 400
                detail: Missing required field `id`
                traceId: b3bf8b06-3fac-4358-9955-4d6653b6f30a
