openapi: 3.1.0
info:
  title: Task Router Proxy
  version: 1.0.0
  description: Forwarding contract for task-prefixed routes served by the gateway.
paths:
  /v1/task/{proxyPath}:
    parameters:
      - name: proxyPath
        in: path
        description: Remaining path segments forwarded to the task orchestrator service.
        required: true
        schema:
          type: string
    get:
      summary: Forward task read requests
      description: Forwards GET requests to the task upstream and streams the response back to the client.
      tags:
        - Task
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response from the upstream task service.
        '401':
          $ref: '#/components/responses/TaskUnauthorizedError'
        '403':
          $ref: '#/components/responses/TaskForbiddenError'
        '502':
          $ref: '#/components/responses/TaskBadGatewayError'
    post:
      summary: Forward task mutating requests
      description: Forwards POST requests to the task orchestrator, preserving JSON bodies and headers.
      tags:
        - Task
      security:
        - bearerAuth: []
      requestBody:
        description: JSON payload forwarded to the task backend.
        required: false
        content:
          application/json:
            schema:
              type: object
      responses:
        '202':
          description: Request accepted by the task pipeline.
        '400':
          $ref: '#/components/responses/TaskBadRequestError'
        '401':
          $ref: '#/components/responses/TaskUnauthorizedError'
        '403':
          $ref: '#/components/responses/TaskForbiddenError'
        '502':
          $ref: '#/components/responses/TaskBadGatewayError'
components:
  schemas:
    TaskProblemJson:
      type: object
      required:
        - type
        - title
        - status
      properties:
        type:
          type: string
          example: about:blank
        title:
          type: string
          example: Authentication Required
        status:
          type: integer
          example: 401
        detail:
          type: string
          example: Missing Authorization header
        instance:
          type: string
          format: uri
          nullable: true
        traceId:
          type: string
          example: 4a95d1b0-bc6b-4645-95f9-0d8f5cbbf671
  securitySchemes:
    taskBearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  responses:
    TaskUnauthorizedError:
      description: Missing or invalid bearer token.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/TaskProblemJson'
          examples:
            missingToken:
              value:
                type: about:blank
                title: Authentication Required
                status: 401
                detail: Missing Authorization header
                traceId: 4a95d1b0-bc6b-4645-95f9-0d8f5cbbf671
    TaskForbiddenError:
      description: Caller lacks required task scopes.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/TaskProblemJson'
          examples:
            scopeMismatch:
              value:
                type: about:blank
                title: Insufficient Scope
                status: 403
                detail: task.write scope required
                traceId: 6c7c1d80-7657-4a5a-9ea4-b5b2db577c96
    TaskBadGatewayError:
      description: Upstream task service is unavailable.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/TaskProblemJson'
          examples:
            upstreamDown:
              value:
                type: about:blank
                title: Upstream Service Unavailable
                status: 502
                detail: Failed to reach task service
                traceId: 694b69c0-e4a4-4d2f-8a74-71b5bdf0a4cb
    TaskBadRequestError:
      description: Upstream validation failed.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/TaskProblemJson'
          examples:
            validationError:
              value:
                type: about:blank
                title: Bad Request
                status: 400
                detail: Missing required field `name`
                traceId: 9b2a1d58-8c95-4f84-9c72-1dae3d1f4f2a
