import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Start Here',
      link: {type: 'doc', id: 'start-here/index'},
      items: [
        'start-here/repo-tour',
        'start-here/local-dev',
        'start-here/request-lifecycle',
        'start-here/glossary',
      ],
    },
    {
      type: 'category',
      label: 'Architecture',
      link: {type: 'doc', id: 'architecture/index'},
      items: [
        'architecture/component-map',
        'architecture/config',
        'architecture/runtime',
        'architecture/server',
        'architecture/proxy',
        'architecture/observability',
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      link: {type: 'doc', id: 'guides/index'},
      items: [
        'guides/running',
        'guides/configuration',
        'guides/auth-cors',
        'guides/websockets',
        'guides/webhooks',
        'guides/openapi',
        'guides/shadowdiff',
        {
          type: 'category',
          label: 'Tooling',
          items: [
            'guides/smoke',
            'guides/shadowdiff-runner',
            'guides/shadowdiff-mocks',
          ],
        },
        'guides/troubleshooting',
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      link: {type: 'doc', id: 'reference/index'},
      items: [
        'reference/config',
        'reference/env',
        'reference/metrics',
        'reference/admin-api',
        'reference/problems',
      ],
    },
    {
      type: 'category',
      label: 'Annotated Source',
      link: {type: 'doc', id: 'annotated/index'},
      items: [{type: 'autogenerated', dirName: 'annotated'}],
    },
    {
      type: 'category',
      label: 'Legacy',
      items: ['legacy'],
    },
  ],

  // Optional: reserved for future versioned docs.
  // apiSidebar: [],
};

export default sidebars;
