name: Go CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  go-build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache-dependency-path: go.sum

      - name: Validate gofmt
        run: |
          files=$(gofmt -l ./cmd ./internal ./pkg)
          if [ -n "$files" ]; then
            echo "Go files not formatted:" >&2
            echo "$files" >&2
            exit 1
          fi

      - name: Go tests
        run: go test ./...

      - name: Go lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60.3
          args: ./...
